# batch_matmul?



In [29]:
import tensorflow as tf
import numpy as np

with tf.Session() as sess:
    # define constants
    x_mat = tf.constant(range(4), shape=[2,2])
    y_mat = tf.constant(range(4), shape=[2,2])
    
    # define matmul op
    m     = tf.matmul(x_mat, y_mat) 

    # eval and print
    print m.eval()
    

m: [[ 2  3]
 [ 6 11]]


In [32]:

with tf.Session() as sess:
    # define placeholder
    x_p = tf.placeholder("float", shape=[2,2])
    y_p = tf.placeholder("float", shape=[2,2])
    
    # define matmul op
    m     = tf.matmul(x_p, y_p) 
    
    # specify input values to placeholder and run
    result = sess.run(m, feed_dict={x_p: np.arange(4).reshape((2, 2)), 
                               y_p: np.arange(4).reshape((2, 2))})
    print result
    

[[  2.   3.]
 [  6.  11.]]


In [38]:

with tf.Session() as sess:
    # define placeholder
    x_p = tf.placeholder("float", shape=[None,2,2])
    y_p = tf.placeholder("float", shape=[None,2,2])
    
    # define batch_matmul op
    m     = tf.batch_matmul(x_p, y_p) 
    
    # specify input values to placeholder and run
    result = sess.run(m, feed_dict={x_p: np.arange(12).reshape((3, 2, 2)), 
                               y_p: np.arange(12).reshape((3, 2, 2))})
    print result
    

[[[   2.    3.]
  [   6.   11.]]

 [[  46.   55.]
  [  66.   79.]]

 [[ 154.  171.]
  [ 190.  211.]]]
